apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170737023
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170737023
    app.kubernetes.io/part-of: test-app-170737023
  name: java-quarkus-170737023
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170737023
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170737023
    spec:
      containers:
      - image: quay.io/hacdev/qxhb8niu-tenant/test-app-170737023/java-quarkus-170737023@sha256:95cb6960c3ae9bd221bd90a8112e372f0f4a0a438a6c28af8960e3e8858f17a3
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
